#!/bin/sh
set -e

. /usr/share/debconf/confmodule

tmp=`mktemp`

if [ -f /etc/dbconfig-common/ndoutils-mysql.conf ] ; then
	dbconfig-load-include -f sh \
		-udbc_dbuser -pdbc_dbpass -ddbc_dbname -sdbc_dbserver -Pdbc_dbport \
		/etc/dbconfig-common/ndoutils-mysql.conf > $tmp
	. $tmp
	if [ -f /usr/share/dbconfig-common/dpkg/frontend.config.mysql ]; then
		. /usr/share/dbconfig-common/dpkg/frontend.config.mysql
		dbc_go nagvis $@
	fi
	db_stop
fi

rm -f $tmp

